name: popper
description: Rem&Coil app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  shared_preferences: any
  flutter_bloc: ^7.3.0
  dio: ^4.0.0
  retrofit: ^2.0.1
  dartz: ^0.10.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  url_launcher: any
  flutter_native_splash: any
  retrofit_generator: any
  build_runner: any
  json_serializable: any
  msix: ^3.1.2

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo1000.png
  web: true
  ios: false
  android: false
  web_image_mode: center


flutter:

  uses-material-design: true

  assets:
    - assets/images/